import { useState } from "react";
import { Link, useRouterState } from "@tanstack/react-router";
import { ArrowUpRight, Menu, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import brandImage from "@/assets/logo-design.jpg";
import webImage from "@/assets/web-build.jpg";
import contentImage from "@/assets/content-shoot.jpg";

export function Logo() { return <Link to="/" className="logo" aria-label="Power Studio home">powerstudio<span className="logo-dot" aria-hidden="true" /></Link>; }
export function Header() {
  const [open, setOpen] = useState(false);
  const path = useRouterState({ select: s => s.location.pathname });
  const links = [{ to: "/start", label: "Start" }, { to: "/grow", label: "Grow" }, { to: "/services", label: "Services" }, { to: "/studio", label: "Studio" }] as const;
  return <><a href="#main" className="skip-link">Skip to content</a><header className="site-header"><div className="topline wrap"><span>POWER STUDIO / CYPRUS</span><span>BRAND DESIGN ✳ WEBSITES ✳ GROWTH</span></div><div className="navbar wrap"><Logo /><Button variant="ghost" size="icon" className="menu-button" aria-label={open ? "Close navigation" : "Open navigation"} aria-expanded={open} aria-controls="site-nav" onClick={() => setOpen(!open)}>{open ? <X size={23}/> : <Menu size={23}/>}</Button><nav id="site-nav" aria-label="Main navigation" className={`navlinks ${open ? "open" : ""}`}>{links.map(l => <Link key={l.to} to={l.to} aria-current={path === l.to ? "page" : undefined} onClick={() => setOpen(false)}>{l.label}</Link>)}<Button asChild className="button" onClick={() => setOpen(false)}><Link to="/contact">LET’S TALK <ArrowUpRight size={17}/></Link></Button></nav></div></header></>;
}
export function Footer() { return <footer className="footer"><div className="wrap footer-main"><div><Logo/><p>A creative and digital studio for businesses ready to begin, build and grow in Cyprus.</p></div><div className="footer-col"><h3>Explore</h3><Link to="/start">Start a business</Link><Link to="/grow">Grow a business</Link><Link to="/services">What we do</Link></div><div className="footer-col"><h3>Studio</h3><Link to="/studio">About us</Link><Link to="/contact">Contact</Link></div><div className="footer-col"><h3>Get in touch</h3><a href="mailto:info@power-cy.com">info@power-cy.com</a><a href="tel:+35799108812">+357 99 108812</a><a href="https://wa.me/35799108812" target="_blank" rel="noopener noreferrer">WhatsApp ↗</a><span>Germasogeia, Cyprus</span></div></div><div className="wrap footer-bottom"><span>© {new Date().getFullYear()} POWER STUDIO</span><span>DESIGNED TO MAKE AN IMPRESSION.</span></div></footer>; }
export function Layout({ children }: {children: React.ReactNode}) { return <><Header/><main id="main">{children}</main><Footer/></>; }
export function Eyebrow({children}:{children:React.ReactNode}) { return <div className="eyebrow">{children}</div>; }
export function CTA() { return <section className="cta-band"><div className="wrap"><Eyebrow>Your next move starts here</Eyebrow><h2 className="display">LET’S MAKE<br/><em>IT MATTER.</em></h2><div className="cta-bottom"><p>Starting with an idea or ready for your next chapter? Tell us what you’re building.</p><Button asChild className="button"><Link to="/contact">TALK TO POWER STUDIO <ArrowUpRight size={18}/></Link></Button></div></div></section>; }
export const services = [
  { number: "01", title: "A brand people remember.", name: "Brand identity", copy: "A logo is only the beginning. We shape the visual language, tone and touchpoints that make your business feel unmistakably yours—from the first introduction to the final detail.", image: brandImage, alt: "Designer shaping a logo on a large monitor in a design application" },
  { number: "02", title: "A website that works harder.", name: "Website development", copy: "A digital home that looks the part and helps people take action. We bring design, clear content and a considered customer journey together across every screen.", image: webImage, alt: "A website being assembled and coded on an ultrawide monitor" },
  { number: "03", title: "Content worth stopping for.", name: "Marketing & content", copy: "Campaign ideas, social media and content creation built around what your audience actually wants to see. Show your products with purpose and keep the conversation moving.", image: contentImage, alt: "Filmmaker shooting promotional product content with a softbox light" },
];
export function ServiceFeatures({ heading = "WHAT WE MAKE WORK.", intro = "A connected presence is made of many parts. Here’s how we bring them together." }: {heading?:string; intro?:string}) { return <section className="section-space wrap" id="services"><div className="section-intro"><div><Eyebrow>The work</Eyebrow><h2 className="display section-title" style={{marginTop: 22}}>{heading}</h2></div><p>{intro}</p></div><div>{services.map(s=><article className="service-feature" key={s.number}><div className="feature-media"><img src={s.image} alt={s.alt} loading="lazy" width={1200} height={912}/></div><div className="feature-copy"><span className="feature-index">{s.number} / {s.name.toUpperCase()}</span><h3>{s.title}</h3><p>{s.copy}</p><Link className="text-link" to="/services">EXPLORE {s.name.toUpperCase()} <ArrowUpRight size={17}/></Link><span className="concept-note">Visual concept, not a Power Studio client project.</span></div></article>)}</div></section>; }
export function PageHero({label,title,accent,copy}:{label:string;title:string;accent:string;copy:string}) { return <section className="page-hero wrap"><Eyebrow>{label}</Eyebrow><h1 className="display">{title}<br/><em>{accent}</em></h1><p>{copy}</p></section>; }
export function head(title:string,description:string) { return { meta: [{title: `${title} | Power Studio`},{name:"description",content:description},{property:"og:title",content:`${title} | Power Studio`},{property:"og:description",content:description},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}] }; }
